### ISSUE TITLE
stack error with v2.5.0

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#1512]
**Environment:**
 - AWS ParallelCluster 2.5.0
 - OS: ubuntu1804
 - Scheduler: SGE
 - Master instance type: t3.micro
 - Compute instance type: several tried

Hello AWS-parallelcluster Team,
Upgrading to 2.5.0 seems to be causing some unexpected behavior. The deployment starts but it never spins up any compute instance. Then, and after stopping the process, the delete command results in the following error message:
```
pcluster delete qgpu1cluster
Deleting: qgpu1cluster
Status: DynamoDBTable - DELETE_COMPLETE                                         ERROR: Stack with id parallelcluster-qgpu1cluster does not exist
```
Thanks

**Comment by enrico-usai** [comment]
Hi @afernandezody 

Thank you for reporting the `pcluster delete` issue. 
It has been already discovered https://github.com/aws/aws-parallelcluster/issues/1485 and fixed in develop. The fix will be part of the next patch release.

I tried to create a cluster with ParallelCluster 2.5.0, Ubuntu1804, t3.micro as master instance type and sge as a scheduler but I haven't encountered problems.

To try to reproduce your issue we need your configuration file without any credentials and personal data, or you can re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node.

If the the cluster creation ends up correctly and you're encountering scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node.
Could you also give us more context about the job you're submitting?

Thank you

**Comment by afernandezody** [comment]
Hi Enrico,
There is no rollback per se as there is no error (the deployment keeps trying to deploy the compute fleet but doesn't spin up any instance). I have to stop the process manually and type the 'pcluster delete' command. The files that you requested are attached. 
The script reads:
```
[aws]
aws_region_name = us-east-1
aws_access_key_id = AKI...
aws_secret_access_key = 3DI...

[cluster qbase0cluster]
vpc_settings = odyvpc
placement_group = DYNAMIC
placement = compute
key_name = ...
master_instance_type = t3.micro
compute_instance_type = c5.large
cluster_type = spot
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
scheduler = sge
base_os = ubuntu1804

[vpc odyvpc]
master_subnet_id = subnet-5118645e
vpc_id = vpc-a73ee9dd

[global]
update_check = true
sanity_check = true
cluster_template = qbase0cluster

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

``` 
Thanks.
P.S. I haven't modified my scripts much for the last few months and haven't made any change moving from 2.4.1 to 2.5.0, not sure if something outdated in the script might be causing the problem, just a thought.

[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/3917649/cfn-init.log)
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/3917650/cfn-init-cmd.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/3917651/cloud-init.log)
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/3917652/cloud-init-output.log)

**Comment by enrico-usai** [comment]
Hi @afernandezody 

thank you for your configuration file.
Now I can tell you that you're facing a know issue with spot instances: https://github.com/aws/aws-parallelcluster/issues/1482

The cluster creation fails (after a timeout of 30 minutes) with the following error:
```
2019-12-03 17:53:38.945000+00:00 CREATE_FAILED AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 0 SUCCESS signal(s) out of 2.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```
By looking to the AutoScalingGroup logs you can see:
```
Launching a new EC2 instance. Status Reason: Value (0.000000) for parameter price is invalid. "0.000000" is an invalid spot instance price. Launching EC2 instance failed.
```
and it's happening because the code is wrongly passing 0.0 as default value for the `spot_price` parameter.

In 2.4.1 the default value was the Spot price, capped at the On-Demand price.
The workaround is to set a [`spot_price`](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#spot-price) different from 0, or a value greater then or equal to the [on-demand price](https://aws.amazon.com/ec2/pricing/on-demand/) for your instance.

The fix has been already merged in the develop branch and it will be part of the next patch release.

**Comment by afernandezody** [comment]
Hi Enrico,
Ha! I knew there had to be some minor difference between 2.4.1 and 2.5.0. Including the spot price has allowed me to deploy the clusters and run some codes. However, the error message is still showing up at the end the cluster deletion. Maybe, it means that the script requires further update, but I just haven't had time to troubleshoot it. Thanks.

**Comment by enrico-usai** [comment]
Hi @afernandezody ,

The error message at the end of the cluster creation is just a misleading message, but the cluster deletion ends up correctly.

I'm going to close this issue, since the problems you're facing are already covered by the #1485 (cluster deletion message) and #1482 (spot price) issues.
The fixes for both the bugs have been already merged in the _develop_ branch and will be part of the next patch release.

Feel free to open a new issue if needed.
Thanks for your feedback.
